language: crystal

addons:
  chrome: stable

services:
  - xvfb

before_install:
  # Setup chromedriver for LuckyFlow
  - sudo apt-get install chromium-chromedriver
  - export DISPLAY=:99.0

script:
  - crystal spec
  - crystal tool format --check
