language: crystal

addons:
  chrome: stable

services:
  - xvfb

before_install:
  # Setup chromedriver for LuckyFlow
  - npm -g install chromedriver --detect_chromedriver_version
  - export DISPLAY=:99.0

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
