name: ExceptionPage CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 0.36.1
          - 1.0.0
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba

  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 0.36.1
          - 1.0.0
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Chromedriver
        run: |
          apt-get update
          apt-get -yqq install chromium-chromedriver
      - name: Cache Crystal
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-crystal
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec
